services:
  db:
    image: mysql:8.0
    container_name: DB_INTEGRADOR_TP2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: DB_INTEGRADOR_TP2
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"
